import {
  Binoculars,
  BookOpenCheck,
  Boxes,
  ClipboardCheck,
  Compass,
  Flag,
  ListChecks,
  Map,
  MapPinned,
  Route,
  ShieldCheck,
  Sparkles,
  UsersRound,
} from "lucide-react";

export const productOne = {
  title: "La Paz desde las alturas a la luna",
  subtitle: "Una vivencia diferente entre el teleférico y el Valle de la Luna",
  description:
    "Un producto turístico inmersivo que conecta paisaje urbano, naturaleza, tecnología accesible y cultura paceña mediante una experiencia participativa y multisensorial.",
};

export const phases = [
  { number: "01", title: "Descubrir", description: "Convertimos la idea inicial en una propuesta clara y compartida." },
  { number: "02", title: "Alinear", description: "Organizamos al equipo, el alcance y los acuerdos de trabajo." },
  { number: "03", title: "Validar", description: "Reducimos incertidumbre antes de invertir en la experiencia completa." },
  { number: "04", title: "Planificar", description: "Ordenamos el valor en lanzamientos y recorridos del usuario." },
  { number: "05", title: "Ejecutar", description: "Transformamos la estrategia en historias listas para trabajar." },
] as const;

export const artifacts = [
  {
    order: 1,
    phase: 0,
    slug: "concepto-del-servicio",
    title: "Concepto del servicio",
    short: "Define la experiencia de principio a fin, su público, los componentes incluidos y aquello que la hace diferente.",
    icon: Compass,
    purpose: "Construir una comprensión común del servicio antes de convertirlo en trabajo ágil.",
    applied: "Conecta las líneas Roja y Plateada de Mi Teleférico con el Valle de la Luna en una ruta de relatos, sonidos, sabores, geología y memoria cultural.",
    evidence: ["Nombre y oportunidad de mercado", "Relato cronológico de la experiencia", "Servicios, seguridad y equipamiento", "Factor de innovación"],
  },
  {
    order: 2,
    phase: 0,
    slug: "vision-del-producto",
    title: "Visión del producto",
    short: "Expresa el propósito y el impacto futuro que orientan cada decisión del equipo.",
    icon: Binoculars,
    purpose: "Dar al equipo una estrella polar breve, memorable y centrada en el visitante.",
    applied: "La experiencia busca que el turista deje de observar La Paz desde fuera y se convierta en protagonista de una conexión emocional con su patrimonio.",
    evidence: ["Segmento objetivo", "Necesidad no resuelta", "Categoría de la experiencia", "Propuesta de valor diferencial"],
  },
  {
    order: 3,
    phase: 0,
    slug: "estrategia-del-producto",
    title: "Estrategia del producto",
    short: "Relaciona clientes, necesidades, atributos del servicio y objetivos de sostenibilidad.",
    icon: Map,
    purpose: "Traducir la visión en decisiones estratégicas comprobables.",
    applied: "Prioriza a viajeros independientes de 22 a 40 años que buscan cultura, fotografía y participación, con tecnología accesible y alianzas locales.",
    evidence: ["Grupo objetivo", "Necesidades del visitante", "Atributos del servicio", "Objetivos del producto"],
  },
  {
    order: 4,
    phase: 1,
    slug: "estructuracion-del-equipo",
    title: "Estructuración del equipo",
    short: "Distribuye responsabilidades de producto, facilitación y desarrollo en un equipo multidisciplinario.",
    icon: UsersRound,
    purpose: "Asegurar que las competencias necesarias estén presentes y que las decisiones tengan responsables claros.",
    applied: "Integra producto, operación turística, interpretación cultural, tecnología, seguridad, marketing y sostenibilidad.",
    evidence: ["Product Owner", "Scrum Master", "Equipo de desarrollo", "Competencias y responsabilidades"],
  },
  {
    order: 5,
    phase: 1,
    slug: "transferencia-de-conocimiento",
    title: "Transferencia de conocimiento",
    short: "Alinea al equipo con un Inception Deck sobre propósito, alcance, prioridades y forma de trabajo.",
    icon: Boxes,
    purpose: "Evitar supuestos distintos antes de iniciar la ejecución.",
    applied: "Aclara qué incluye el piloto, qué queda fuera, cómo se medirá el éxito y cuáles son los principales acuerdos operativos.",
    evidence: ["Por qué estamos aquí", "Elevator pitch", "Alcance IN y OUT", "Prioridades y acuerdos"],
  },
  {
    order: 6,
    phase: 2,
    slug: "matriz-de-riesgos",
    title: "Matriz de riesgos",
    short: "Evalúa las incertidumbres de deseabilidad, factibilidad, viabilidad y usabilidad.",
    icon: ShieldCheck,
    purpose: "Anticipar obstáculos y definir acciones antes de que comprometan la experiencia.",
    applied: "Considera permisos, seguridad, conectividad, funcionamiento de audios, coordinación del transporte y respuesta del mercado.",
    evidence: ["Riesgo identificado", "Probabilidad e impacto", "Nivel de exposición", "Respuesta y responsable"],
  },
  {
    order: 7,
    phase: 2,
    slug: "producto-minimo-viable",
    title: "Producto Mínimo Viable",
    short: "Diseña la versión más pequeña de la experiencia capaz de producir aprendizaje real.",
    icon: Sparkles,
    purpose: "Validar las hipótesis críticas con visitantes antes del lanzamiento completo.",
    applied: "Prueba un recorrido acotado por las líneas Roja y Plateada y tres estaciones del Valle de la Luna con 15 participantes.",
    evidence: ["Hipótesis de valor", "Alcance incluido y excluido", "Recursos estimados", "Métricas de éxito"],
  },
  {
    order: 8,
    phase: 3,
    slug: "hoja-de-ruta",
    title: "Hoja de ruta del producto",
    short: "Organiza el crecimiento del servicio en lanzamientos con metas y resultados medibles.",
    icon: Route,
    purpose: "Mostrar cómo evoluciona el producto desde el piloto hasta una oferta escalable.",
    applied: "Propone tres horizontes: piloto seguro, operación comercial y experiencias premium mediante alianzas.",
    evidence: ["Horizontes temporales", "Meta por lanzamiento", "Características clave", "Métricas de éxito"],
  },
  {
    order: 9,
    phase: 3,
    slug: "mapeo-de-historias",
    title: "Mapeo de historias de usuario",
    short: "Visualiza el viaje del visitante y prioriza las historias necesarias para cada lanzamiento.",
    icon: MapPinned,
    purpose: "Mantener visible el flujo completo de valor y realizar cortes de entrega coherentes.",
    applied: "Recorre descubrimiento y reserva, preparación y traslado, vivencia, evaluación y retorno.",
    evidence: ["Actividades del visitante", "Pasos del recorrido", "Historias del MVP", "Cortes comercial y de escalamiento"],
  },
  {
    order: 10,
    phase: 4,
    slug: "product-backlog",
    title: "Gestión del Product Backlog",
    short: "Convierte las necesidades del visitante en historias priorizadas, estimables y comprobables.",
    icon: ListChecks,
    purpose: "Crear una única fuente de trabajo ordenada por valor, riesgo y aprendizaje.",
    applied: "Incluye reservas con QR, audioguía en el teleférico y exploración sensorial del Valle de la Luna.",
    evidence: ["Historia en formato estándar", "Criterios de aceptación BDD", "Prioridad", "Story Points"],
  },
  {
    order: 11,
    phase: 4,
    slug: "definition-of-ready",
    title: "Definición de preparación",
    short: "Comprueba que una historia está clara, estimada y lista antes de entrar al Sprint.",
    icon: ClipboardCheck,
    purpose: "Evitar iniciar trabajo ambiguo o bloqueado.",
    applied: "La audioguía se considera preparada cuando tiene criterios medibles, permisos revisados, dispositivos disponibles y estimación del equipo.",
    evidence: ["Valor claramente expresado", "Criterios medibles", "Factibilidad operativa", "Estimación compartida"],
  },
  {
    order: 12,
    phase: 4,
    slug: "definition-of-done",
    title: "Definición de Hecho",
    short: "Establece el estándar común que todo incremento debe cumplir para considerarse terminado.",
    icon: BookOpenCheck,
    purpose: "Garantizar una calidad consistente en cada entrega.",
    applied: "Exige simulación del recorrido, permisos vigentes, materiales bilingües, protocolos de seguridad y aprobación del Product Owner.",
    evidence: ["Prueba en campo", "Cumplimiento legal", "Comunicación revisada", "Seguridad y aprobación"],
  },
  {
    order: 13,
    phase: 4,
    slug: "planificacion-de-sprints",
    title: "Planificación y ejecución de Sprints",
    short: "Selecciona un objetivo, organiza el Sprint Backlog y acuerda cómo inspeccionar el avance.",
    icon: Flag,
    purpose: "Coordinar entregas cortas de valor con aprendizaje y mejora continua.",
    applied: "El primer Sprint valida reserva, seguridad del traslado y audioguía, con Daily, Sprint Review y Retrospective definidos.",
    evidence: ["Sprint Goal", "Sprint Backlog", "Tareas multidisciplinarias", "Eventos de control"],
  },
] as const;

export type ProductArtifact = (typeof artifacts)[number];

export function getArtifact(slug: string) {
  return artifacts.find((artifact) => artifact.slug === slug);
}
