export type DetailBlock = { title: string; lead?: string; items: string[]; meta?: string; score?: string };

export type RemainingArtifact = {
  order: number; slug: string; title: string; accent: string; image: string; imageAlt: string;
  eyebrow: string; heroLead: string; definition: string; purpose: string;
  templateTitle: string; templateIntro: string; template: DetailBlock[];
  appliedTitle: string; appliedIntro: string; applied: DetailBlock[];
  closingTitle: string; closingText: string;
};

export const remainingArtifacts: RemainingArtifact[] = [
  {
    order: 4, slug: "estructuracion-del-equipo", title: "Estructuración del equipo", accent: "#c98255", image: "/artifact-team.webp", imageAlt: "Equipo multidisciplinario planifica una experiencia turística en La Paz",
    eyebrow: "Fase 02 · Alinear · Artefacto 04", heroLead: "Las personas, capacidades y responsabilidades necesarias para convertir la visión en una experiencia segura y memorable.",
    definition: "En Scrum, el equipo se basa en la autogestión y la multidisciplinariedad. Este artefacto formaliza los roles críticos para que todas las competencias necesarias puedan transformar el Product Backlog en incrementos de valor.",
    purpose: "Aclarar quién decide, quién facilita y quién construye, evitando vacíos de responsabilidad y mejorando la colaboración.",
    templateTitle: "Tres responsabilidades que trabajan como una sola", templateIntro: "La plantilla distribuye la estrategia, la facilitación y el desarrollo entre roles complementarios.",
    template: [
      { title: "Product Owner", meta: "Estrategia de producto", items: ["Maximiza el valor del servicio.", "Gestiona y prioriza el Product Backlog."] },
      { title: "Scrum Master", meta: "Facilitación ágil", items: ["Promueve Scrum.", "Ayuda a eliminar impedimentos y mejorar la forma de trabajo."] },
      { title: "Developers", meta: "Equipo multidisciplinario", items: ["Integran operaciones turísticas, asesoría legal, marketing, ambiente, tecnología, cultura y gastronomía."] },
    ],
    appliedTitle: "El equipo detrás de la expedición", appliedIntro: "Ocho perfiles coordinan producto, experiencia, tecnología, operación y cultura.",
    applied: [
      { title: "Product Owner", meta: "Gestor del proyecto turístico", items: ["Define la visión e identifica necesidades del turista.", "Prioriza el backlog y analiza la viabilidad económica.", "Representa al cliente y valida el valor comercial con el GAMLP."] },
      { title: "Scrum Master", meta: "Facilitación ágil", items: ["Organiza eventos Scrum y coordina reuniones.", "Ayuda a aplicar Scrum, resolver obstáculos y mejorar continuamente.", "Facilita la coordinación entre áreas."] },
      { title: "Especialista en turismo", meta: "Diseño de la experiencia", items: ["Diseña recorrido, estaciones, misiones y tiempos.", "Integra teleférico y Valle de la Luna.", "Define el plan de bajo impacto, cero residuos y supervisión de ruta."] },
      { title: "Diseñador tecnológico", meta: "Realidad aumentada y multimedia", items: ["Desarrolla realidad aumentada, audioguías, música y sonidos ambientales.", "Produce videos y fotografías."] },
      { title: "Guía intérprete", meta: "Operaciones turísticas", items: ["Investiga cultura e historia.", "Diseña estaciones, desafíos, relatos y contenidos.", "Explica el recorrido y selecciona música y ambientes sonoros."] },
      { title: "Marketing y ventas", meta: "Comercialización", items: ["Gestiona marketing digital, videos y branding.", "Crea alianzas con hoteles y agencias.", "Configura reservas y cobro mediante QR."] },
      { title: "Asesoría legal y seguridad", meta: "Normativa y gestión de riesgos", items: ["Gestiona permisos, convenios, seguros y deslindes.", "Define protocolos de emergencia, accesibilidad y condiciones del recorrido.", "Coordina la seguridad operativa."] },
      { title: "Gastronomía y souvenirs", meta: "Experiencia local", items: ["Diseña la degustación de productos bolivianos.", "Gestiona souvenirs, materiales, vestimenta y señalética."] },
    ], closingTitle: "Un equipo diverso crea una experiencia más completa.", closingText: "Scrum reúne las capacidades necesarias y hace visible quién aporta valor en cada decisión."
  },
  {
    order: 5, slug: "transferencia-de-conocimiento", title: "Transferencia de conocimiento", accent: "#b76c45", image: "/artifact-inception.webp", imageAlt: "Equipo alinea una ruta turística mediante mapas y notas visuales",
    eyebrow: "Fase 02 · Alinear · Artefacto 05", heroLead: "Un Inception Deck para que todas las personas compartan el mismo propósito, alcance, prioridades y forma de construir.",
    definition: "El Inception Deck es una herramienta de alineación táctica compuesta por diez actividades. Permite compartir una visión común sobre el alcance, las exclusiones, la solución técnica y las prioridades de ejecución.", purpose: "Reducir supuestos, anticipar desacuerdos y comenzar el trabajo con criterios compartidos.",
    templateTitle: "Diez conversaciones antes de comenzar", templateIntro: "Cada actividad responde una pregunta que el equipo necesita resolver en conjunto.",
    template: [
      {title:"¿Por qué estamos aquí?",items:["Define el propósito central y los objetivos que motivan la inversión."]},{title:"Elevator Pitch",items:["Resume cliente, problema, solución y valor en 30 segundos."]},{title:"Diseño de la caja",items:["Identifica el beneficio principal y el eslogan del producto."]},{title:"Lista del NO",items:["Aclara qué está dentro y fuera del alcance."]},{title:"Vecindario",items:["Mapea actores, proveedores y aliados."]},{title:"Solución técnica",items:["Visualiza plataformas y herramientas necesarias."]},{title:"Qué nos quita el sueño",items:["Expone los riesgos que podrían detener el proyecto."]},{title:"Tamaño de la criatura",items:["Estima tiempo y recursos humanos."]},{title:"Trade-offs",items:["Acuerda prioridades entre costo, tiempo, calidad y alcance."]},{title:"¿Qué se necesita?",items:["Lista recursos, presupuesto y aprobaciones."]},
    ],
    appliedTitle: "El acuerdo inicial de la experiencia", appliedIntro: "El equipo define el producto antes de invertir en su construcción.",
    applied: [
      {title:"1. Propósito",items:["Crear una experiencia inmersiva entre el teleférico y el Valle de la Luna mediante sentidos, tecnología, cultura y desafíos de exploración."]},
      {title:"2. Elevator Pitch",items:["¿Y si conocer La Paz fuera una misión? El visitante descubre historias y paisajes desde el teleférico y se convierte en explorador en el Valle de la Luna. No viene solamente a mirar La Paz: viene a vivirla."]},
      {title:"3. La caja",meta:"La Paz entre el cielo y la luna",items:["Beneficio: aventura, cultura, naturaleza, tecnología y emoción en una sola experiencia."]},
      {title:"4. Alcance",meta:"IN / OUT",items:["IN: guías bilingües, transporte, teleférico, audio, relatos, Valle de la Luna, realidad aumentada, estaciones, fotografías, vestimenta y danza.","OUT: alcohol, pernocte, equipos especializados de realidad virtual, alojamiento, restaurante propio y modificación de instalaciones."]},
      {title:"5. Vecindario",items:["GAMLP y administración del Valle de la Luna.","Mi Teleférico, operadores, agencias, hoteles y restaurantes.","Guías, artesanos y emprendimientos gastronómicos."]},
      {title:"6. Solución técnica",items:["Smartphones, audios, plataforma web y realidad aumentada en navegador.","Biblioteca sonora, contenido audiovisual y WhatsApp Business para reservas."]},
      {title:"7. Insomnio",items:["Problemas tecnológicos, impacto ambiental y clima.","Bloqueos, baja rentabilidad, permisos y poca participación."]},
      {title:"8. Tamaño",items:["Diseño y lanzamiento: tres meses.","Equipo central: seis especialistas multidisciplinarios."]},
      {title:"9. Trade-offs",items:["No negociables: seguridad y calidad.","Flexible: alcance inicial de funcionalidades digitales."]},
      {title:"10. Necesidad",meta:"Presupuesto piloto: Bs 14.000",items:["Equipo humano de guía, experiencia, tecnología, marketing, audiovisual, operación y seguridad.","Celulares, audífonos, realidad aumentada y edición de video.","Degustación, vestimenta, dron, fotografía, permisos y aprobaciones."]},
    ], closingTitle:"Alinear primero permite avanzar con confianza.",closingText:"El Inception Deck convierte expectativas dispersas en decisiones visibles para todo el equipo."
  },
  {
    order:6,slug:"matriz-de-riesgos",title:"Matriz de riesgos",accent:"#b45f46",image:"/artifact-risk.webp",imageAlt:"Especialistas inspeccionan la seguridad de una ruta en el Valle de la Luna",eyebrow:"Fase 03 · Validar · Artefacto 06",heroLead:"Detectar la incertidumbre antes de que afecte al visitante, la operación o la sostenibilidad del servicio.",definition:"La matriz de riesgos evalúa proactivamente las incertidumbres que podrían comprometer el éxito del servicio en cuatro dimensiones: deseabilidad, factibilidad, viabilidad y usabilidad.",purpose:"Priorizar amenazas según su probabilidad e impacto y acordar una acción de mitigación concreta.",templateTitle:"Cuatro preguntas para anticiparse",templateIntro:"Cada categoría observa una condición esencial del producto.",template:[{title:"Deseabilidad",items:["¿Los visitantes quieren esta experiencia?"]},{title:"Factibilidad",items:["¿Podemos construirla y operarla?"]},{title:"Viabilidad",items:["¿Puede sostenerse económicamente?"]},{title:"Usabilidad",items:["¿Las personas pueden comprenderla y utilizarla?"]}],appliedTitle:"Riesgos críticos y respuestas",appliedIntro:"Probabilidad e impacto se califican de 1, bajo, a 5, alto.",applied:[{title:"R01 · Deseabilidad",score:"P 2 · I 3",lead:"Poco interés en combinar teleférico, tecnología y Valle de la Luna.",items:["Validar mediante encuestas y pilotos con turistas nacionales y extranjeros.","Ajustar las actividades según sus preferencias."]},{title:"R02 · Factibilidad",score:"P 3 · I 4",lead:"Conectividad, clima o condiciones del lugar afectan la realidad aumentada y los audios.",items:["Precargar contenidos y ofrecer audios offline como respaldo."]},{title:"R03 · Viabilidad",score:"P 4 · I 3",lead:"Tecnología, guías, degustaciones, souvenirs y audiovisual reducen la rentabilidad.",items:["Comenzar con un MVP de bajo costo.","Usar tecnología accesible y alianzas con proveedores locales."]},{title:"R04 · Usabilidad",score:"P 2 · I 2",lead:"Algunos visitantes pueden tener dificultades con la realidad aumentada.",items:["Ofrecer instrucciones simples, demostración inicial y acompañamiento permanente del guía."]}],closingTitle:"Prevenir también forma parte de la experiencia.",closingText:"Gestionar riesgos protege al visitante y permite aprender sin comprometer la operación."
  },
  {
    order:7,slug:"producto-minimo-viable",title:"Producto Mínimo Viable",accent:"#c98345",image:"/artifact-mvp.webp",imageAlt:"Viajeros prueban audífonos y una reserva QR antes de abordar el teleférico",eyebrow:"Fase 03 · Validar · Artefacto 07",heroLead:"La versión más pequeña de la experiencia capaz de comprobar si el visitante realmente la desea y está dispuesto a pagar por ella.",definition:"El MVP permite recolectar la mayor cantidad de aprendizaje validado sobre los clientes con el menor esfuerzo posible. No es un producto incompleto: es un experimento diseñado para validar hipótesis críticas.",purpose:"Probar valor, precio, seguridad y operación antes de invertir en la experiencia completa.",templateTitle:"Cinco decisiones para una prueba útil",templateIntro:"La plantilla define qué se comprobará, qué se incluirá y cómo se medirá el resultado.",template:[{title:"Hipótesis principal",items:["Creemos que un grupo realizará una acción o pago; lo sabremos mediante una métrica concreta."]},{title:"Alcance incluido",items:["Servicios mínimos indispensables del piloto."]},{title:"Alcance excluido",items:["Componentes simulados, manuales o postergados."]},{title:"Costo y recursos",items:["Presupuesto, personas e insumos indispensables."]},{title:"Métricas de éxito",items:["Indicadores que validan o refutan la hipótesis."]}],appliedTitle:"El piloto de La Paz desde las alturas a la luna",appliedIntro:"Una prueba con 15 cupos, precio real y criterios verificables.",applied:[{title:"Hipótesis central",meta:"Bs 300 por persona",items:["Turistas extranjeros de 22 a 40 años pagarán por una experiencia que combina teleférico, Valle de la Luna, sonidos, sabores y cultura.","Éxito: vender 15 cupos en siete días; 70% completa y recomendaría o repetiría la experiencia."]},{title:"Alcance incluido",items:["Reserva web y cobro QR manual.","Recojo, líneas Roja y Plateada con relatos y topografía paceña.","Circuito corto del Valle de la Luna con guía.","Estaciones Tierra, Sabores y Aromas, y Memoria Cultural.","Degustación boliviana, vestimenta, baile, fotografías, videos y souvenir."]},{title:"Alcance excluido",items:["Realidad virtual especializada y desarrollo tecnológico avanzado.","Transporte propio, experiencias nocturnas e inteligencia artificial.","Recorrido por todas las líneas de teleférico."]},{title:"Costo estimado",meta:"Total Bs 1.800",items:["Transporte: Bs 800.","Refrigerios: Bs 400.","Seguro diario: Bs 300.","Promoción en redes: Bs 300."]},{title:"Criterios de éxito",items:["NPS superior a 80% y al menos 60% con intención de recomendar o recomprar.","Cero incidentes de seguridad o salud.","15 reservas confirmadas y pagadas previamente."]}],closingTitle:"Probar pequeño para aprender rápido.",closingText:"El piloto transforma supuestos en evidencia antes de ampliar la inversión."
  },
  {
    order:8,slug:"hoja-de-ruta",title:"Hoja de ruta del producto",accent:"#9a7148",image:"/artifact-roadmap.webp",imageAlt:"Equipo organiza los tres lanzamientos futuros del producto turístico",eyebrow:"Fase 04 · Planificar · Artefacto 08",heroLead:"Tres lanzamientos convierten el piloto en una operación comercial y luego en una experiencia premium.",definition:"La GO Product Roadmap organiza la evolución del servicio por resultados y metas, en vez de limitarse a una lista de funcionalidades.",purpose:"Alinear cada horizonte temporal con una meta estratégica, características y métricas comprobables.",templateTitle:"Cada lanzamiento responde cuatro preguntas",templateIntro:"Cuándo ocurre, qué busca lograr, qué incorpora y cómo sabremos que funcionó.",template:[{title:"Horizonte",items:["Marco temporal del lanzamiento."]},{title:"Nombre",items:["Descripción clara de la versión."]},{title:"Meta",items:["Resultado estratégico que se busca lograr."]},{title:"Características",items:["Funciones que respaldan la meta."]},{title:"Métricas",items:["Indicadores para comprobar el resultado."]}],appliedTitle:"Doce meses para crecer con evidencia",appliedIntro:"La ruta avanza del piloto seguro a una oferta internacional y escalable.",applied:[{title:"Lanzamiento 1",meta:"Meses 1–3 · Piloto de prueba",lead:"Validar la seguridad y lograr aprobación formal del GAMLP.",items:["Convenio de gobernanza, primeros auxilios y evacuación.","Reserva web y QR manual; señalética, vestimenta, souvenir y gastronomía.","Meta: convenio firmado, ruta sin riesgos, 10 participantes sin incidentes y NPS superior al 80%."]},{title:"Lanzamiento 2",meta:"Meses 4–7 · Operación comercial",lead:"Consolidar ventas semanales y posicionar la marca digital.",items:["Pauta automatizada, pago QR automático y guion bilingüe.","Transporte regular con GPS.","Meta: 60 turistas al mes, CAC menor a Bs 25 y 15% de conversión."]},{title:"Lanzamiento 3",meta:"Meses 8–12 · Experiencias premium",lead:"Expandirse hacia turistas internacionales, hoteles y grupos corporativos.",items:["Alianzas con hoteles, fotografía, 360°, dron y audioguías multilingües.","Gastronomía ampliada y paquetes privados.","Meta: 120 turistas al mes, 65% internacionales, tres contratos y 35% más ingresos."]}],closingTitle:"Crecer sin perder el rumbo.",closingText:"Cada lanzamiento añade valor cuando el anterior demuestra que funciona."
  },
];

export const executionArtifacts: RemainingArtifact[] = [
  {
    order:9,slug:"mapeo-de-historias",title:"Mapeo de historias de usuario",accent:"#7b7650",image:"/artifact-storymap.webp",imageAlt:"Equipo organiza visualmente el viaje completo del visitante",eyebrow:"Fase 04 · Planificar · Artefacto 09",heroLead:"El viaje completo del visitante, organizado de principio a fin y dividido en entregas que siempre generan valor.",definition:"El User Story Mapping es una matriz bidimensional: el eje horizontal representa los pasos secuenciales del viaje y el vertical organiza las historias por prioridad. Las épicas forman el esqueleto del backlog.",purpose:"Mantener visible el flujo de valor completo y realizar cortes coherentes para el MVP, el lanzamiento comercial y el escalamiento.",templateTitle:"Una experiencia vista como recorrido",templateIntro:"Cuatro etapas conectan actividades, pasos e historias de usuario.",template:[{title:"Descubrimiento y reserva",items:["Conocer la propuesta, elegir, registrarse y pagar."]},{title:"Preparación y traslado",items:["Recibir información, encontrarse y viajar con seguridad."]},{title:"Vivencia",items:["Escuchar, explorar e interactuar."]},{title:"Evaluación y retorno",items:["Opinar, recibir recuerdos y recomendar."]}],appliedTitle:"Tres cortes de entrega sobre un mismo viaje",appliedIntro:"Cada versión amplía la experiencia sin romper su secuencia.",applied:[{title:"1. Descubrir y reservar",items:["MVP: video promocional; formulario y QR manual.","Comercial: calendario interactivo y QR automático.","Escalamiento: paquetes corporativos, para hoteles y agencias."]},{title:"2. Prepararse y trasladarse",items:["MVP: recomendaciones por WhatsApp; lista, seguro y orientación.","Comercial: ubicación del transporte mediante GPS.","Escalamiento: recojo privado desde el hotel."]},{title:"3. Vivir el destino",items:["MVP: líneas Roja y Plateada con audioguía; estaciones Tierra, Sabores y Aromas, Memoria Cultural.","Comercial: audioguía bilingüe y cinco estaciones con realidad aumentada offline.","Escalamiento: fotografía profesional, 360°, dron y gastronomía ampliada."]},{title:"4. Evaluar y retornar",items:["MVP: encuesta NPS y recuerdo digital.","Comercial: galería privada y descuento para referidos.","Escalamiento: descarga de fotografías y videos en alta resolución."]}],closingTitle:"Cuando el viaje es visible, el valor también lo es.",closingText:"El mapa ayuda a priorizar sin perder la experiencia completa del visitante."
  },
  {
    order:10,slug:"product-backlog",title:"Gestión del Product Backlog",accent:"#b06c47",image:"/artifact-backlog.webp",imageAlt:"Product Owner prioriza historias de usuario para la experiencia turística",eyebrow:"Fase 05 · Ejecutar · Artefacto 10",heroLead:"Una fuente única de trabajo que transforma necesidades del visitante en historias claras, priorizadas y comprobables.",definition:"El Product Backlog reúne historias de usuario que cumplen INVEST: independientes, negociables, valiosas, estimables, pequeñas y testeables. Cada historia incluye criterios de aceptación BDD.",purpose:"Ordenar el trabajo por valor, aprendizaje y riesgo, manteniendo una descripción verificable de lo que necesita el visitante.",templateTitle:"De una necesidad a una historia lista",templateIntro:"Cada elemento expresa rol, deseo, beneficio, condiciones de aceptación, prioridad y estimación.",template:[{title:"Historia",items:["Como [rol], quiero [acción], para [beneficio]."]},{title:"Criterios BDD",items:["Dado un contexto, cuando ocurre una acción, entonces debe observarse un resultado."]},{title:"Prioridad",items:["Orden según valor, riesgo y dependencia."]},{title:"Story Points",items:["Estimación compartida mediante escala Fibonacci."]}],appliedTitle:"Tres historias prioritarias",appliedIntro:"Reserva, audioguía y exploración sensorial forman el núcleo de la experiencia.",applied:[{title:"HU-01 · Reserva y QR",meta:"Alta · 3 puntos",lead:"Como turista digital, quiero reservar y pagar por QR para confirmar mi cupo rápidamente.",items:["Datos completos → mostrar QR válido.","Pago confirmado → enviar confirmación y punto de encuentro.","Error y reintento → conservar los datos."]},{title:"HU-05 · Audioguía inmersiva",meta:"Alta · 5 puntos",lead:"Como visitante cultural, quiero escuchar relatos y música para comprender La Paz mientras viajo.",items:["Reproducir contenido correspondiente a cada tramo.","Funcionar sin conexión.","Reproducir el idioma seleccionado."]},{title:"HU-06 · Exploración sensorial",meta:"Alta · 8 puntos",lead:"Como turista experiencial, quiero participar en estaciones para descubrir el Valle de la Luna con los sentidos.",items:["Explicar dinámica y normas ambientales.","Entregar contenido cultural o natural verificable.","Activar contenidos offline si falla la tecnología."]}],closingTitle:"El backlog convierte deseos en trabajo verificable.",closingText:"Cada historia conecta una necesidad real con una condición clara de valor."
  },
  {
    order:11,slug:"definition-of-ready",title:"Definición de preparación",accent:"#8a7655",image:"/artifact-ready.webp",imageAlt:"Equipo verifica equipos, seguridad y contenidos antes de iniciar el trabajo",eyebrow:"Fase 05 · Ejecutar · Artefacto 11",heroLead:"El acuerdo que evita comenzar trabajo ambiguo, bloqueado o imposible de completar durante el Sprint.",definition:"La Definition of Ready es un estándar que asegura que una historia es suficientemente clara, pequeña y factible para entrar al Sprint Planning.",purpose:"Reducir desperdicio comprobando valor, criterios, permisos, operación, seguridad y estimación antes de iniciar.",templateTitle:"Cinco condiciones para comenzar",templateIntro:"Una historia está preparada cuando el equipo puede comprenderla, probarla y completarla.",template:[{title:"Claridad y valor",items:["Formato como, quiero, para y beneficio explícito."]},{title:"Criterios medibles",items:["Al menos tres condiciones claras y verificables."]},{title:"Viabilidad legal",items:["Normas y permisos identificados; sin bloqueos pendientes."]},{title:"Factibilidad y seguridad",items:["Logística, rutas, primeros auxilios y actores confirmados."]},{title:"Estimación",items:["Puntos Fibonacci acordados y tamaño posible en un Sprint."]}],appliedTitle:"HU-05 está preparada",appliedIntro:"La audioguía inmersiva supera todas las verificaciones antes de entrar al Sprint.",applied:[{title:"Historia clara",score:"Cumple",items:["Rol, acción y valor explican la necesidad de comprender paisaje y cultura durante el traslado."]},{title:"Aceptación medible",score:"Cumple",items:["Tres criterios verifican reproducción por tramo, funcionamiento offline e idioma."]},{title:"Permisos y gobernanza",score:"Cumple",items:["Condiciones de Mi Teleférico, trabajo del guía y uso de audífonos revisados."]},{title:"Operación y seguridad",score:"Cumple",items:["Audios cargados, audífonos disponibles y prueba técnica realizada en líneas Roja y Plateada."]},{title:"Estimación",score:"Cumple · 5 puntos",items:["El equipo confirma que puede completarse en un Sprint."]}],closingTitle:"Estar preparado también es crear valor.",closingText:"Una buena entrada al Sprint reduce interrupciones y protege el foco del equipo."
  },
  {
    order:12,slug:"definition-of-done",title:"Definición de Hecho",accent:"#667a5e",image:"/artifact-done.webp",imageAlt:"Equipo valida en campo la calidad final de una experiencia turística",eyebrow:"Fase 05 · Ejecutar · Artefacto 12",heroLead:"El estándar común que garantiza que cada entrega esté realmente terminada, probada, segura y aprobada.",definition:"La Definition of Done es un acuerdo transversal sobre lo que significa que un trabajo está terminado. Se aplica a todos los elementos del backlog para mantener un estándar de calidad institucional.",purpose:"Evitar entregas incompletas y asegurar que valor, operación, comunicación, seguridad y aprobación estén presentes.",templateTitle:"Cinco evidencias para terminar",templateIntro:"Completar una tarea no basta: el incremento debe funcionar y cumplir el estándar acordado.",template:[{title:"Simulación en campo",items:["Protocolo, guion o actividad probado y cronometrado."]},{title:"Cumplimiento legal",items:["Deslinde, seguro y autorizaciones vigentes."]},{title:"Comunicación",items:["Material revisado, traducido y sin errores."]},{title:"Seguridad y sostenibilidad",items:["Emergencia, evacuación y cero residuos verificados."]},{title:"Aprobación",items:["Product Owner comprueba criterios y da conformidad."]}],appliedTitle:"El incremento cumple el estándar",appliedIntro:"La prueba piloto fue verificada integralmente antes de declararse terminada.",applied:[{title:"Calidad operativa",score:"Cumple",items:["Líneas Roja y Plateada y circuito corto ensayados, cronometrados y validados."]},{title:"Legal y riesgos",score:"Cumple",items:["Deslinde, seguro, coordinación con Mi Teleférico y autorizaciones vigentes."]},{title:"Comunicación",score:"Cumple",items:["Guiones, audios, instrucciones, señalética y formularios revisados en español e inglés."]},{title:"Seguridad",score:"Cumple",items:["Botiquín, GPS, emergencias, residuos y alternativas offline verificados."]},{title:"Product Owner",score:"Cumple",items:["Participó en la simulación, comprobó criterios y aprobó el incremento."]}],closingTitle:"Terminado significa listo para generar valor.",closingText:"La calidad compartida protege al visitante y evita trasladar problemas a la siguiente entrega."
  },
  {
    order:13,slug:"planificacion-de-sprints",title:"Planificación y ejecución de Sprints",accent:"#a26343",image:"/artifact-sprint.webp",imageAlt:"Equipo turístico coordina su Sprint frente a un tablero de trabajo",eyebrow:"Fase 05 · Ejecutar · Artefacto 13",heroLead:"Un ciclo corto para seleccionar valor, coordinar especialidades, demostrar resultados y mejorar la siguiente entrega.",definition:"La planificación del Sprint define el valor que se entregará durante un ciclo de una a cuatro semanas. El equipo acuerda el Sprint Goal, el Sprint Backlog y el desglose de tareas.",purpose:"Coordinar trabajo multidisciplinario con un objetivo común y eventos frecuentes de inspección y adaptación.",templateTitle:"Cinco acuerdos para ejecutar",templateIntro:"La planificación conecta el mapa de historias con la entrega diaria y el aprendizaje del equipo.",template:[{title:"Sprint Goal",items:["Seleccionar el corte y formular un objetivo unificado."]},{title:"Sprint Backlog",items:["Elegir historias de descubrimiento, preparación, vivencia y evaluación."]},{title:"Tareas",items:["Desglosar trabajo para legal, operación, marketing, cultura y ambiente."]},{title:"DoR y DoD",items:["Confirmar preparación y comprometer el estándar de terminado."]},{title:"Eventos Scrum",items:["Acordar Daily, Sprint Review y Retrospective."]}],appliedTitle:"Sprint 1 · Primera venta de 15 cupos",appliedIntro:"Meta: validar reserva, seguridad del traslado y audioguía del recorrido piloto.",applied:[{title:"Sprint Backlog",items:["HU01 video promocional · 3 puntos.","HU02 formulario y QR manual · 3 puntos.","HU03 recomendaciones por WhatsApp · 2 puntos.","HU04 lista y seguro activo · 5 puntos.","HU05 teleférico con audioguía · 5 puntos."]},{title:"Tareas multidisciplinarias",items:["Marketing graba y edita el video.","Tecnología configura formulario y QR.","Operaciones prepara recomendaciones y encuentro.","Legal tramita póliza y control de pasajeros.","Contenido produce relatos; operaciones prueba audífonos offline."]},{title:"Calidad acordada",items:["DoR: criterios, estimación, responsables, permisos y recursos disponibles.","DoD: prueba técnica, simulación, revisión bilingüe y aprobación del Product Owner."]},{title:"Daily",meta:"Lunes a viernes · 08:30 · Discord",items:["Máximo 15 minutos para sincronizar avance e impedimentos."]},{title:"Review y Retrospective",meta:"Segundo viernes · 18:00 y 19:00",items:["Review: demostrar video, QR, traslado y audioguía.","Retrospective: revisar coordinación, tiempos, fallos y mejoras."]}],closingTitle:"Entregar, aprender y volver a mejorar.",closingText:"El Sprint convierte la estrategia en resultados visibles sin perder capacidad de adaptación."
  },
];

export function getRemainingArtifact(slug:string){return [...remainingArtifacts,...executionArtifacts].find(item=>item.slug===slug)}
